---
- hosts: master

  vars_files:
    - ../../config/config.yml

  pre_tasks:
    - name: Ensure apt-transport-https is installed.
      apt: name=apt-transport-https state=present

  roles:
    - geerlingguy.mysql
    - geerlingguy.nodejs

  tasks:
    - name: Ensure the temperature-monitor repository is present.
      git:
        repo: https://github.com/geerlingguy/temperature-monitor.git
        dest: "{{ temperature_monitor_dir }}"
        update: yes
      when: deploy_target_is_pi

    - include: tasks/database.yml
    - include: tasks/app.yml
    - include: tasks/scripts.yml
