---
- hosts: master
  become: true

  vars_files:
    - ../../config/config.yml

  pre_tasks:
    - name: Ensure apt cache is updated.
      apt: update_cache=true cache_valid_time=86400

    - name: Ensure apt-transport-https is installed.
      apt: name=apt-transport-https state=present

  roles:
    - geerlingguy.git
    - geerlingguy.mysql
    - geerlingguy.nodejs
    - role: geerlingguy.raspberry-pi
      when: deploy_target_is_pi

  tasks:
    - name: Install dependencies for Python temperature scripts.
      apt:
        name:
          - python-pip
          - python-dev
        state: present

    - name: Clean up bad Python requests package so pip works.
      shell: "rm -rf /usr/local/lib/python2.7/dist-packages/requests*"
      changed_when: false

    - name: Ensure the temperature-monitor repository is present.
      git:
        repo: https://github.com/geerlingguy/temperature-monitor.git
        dest: "{{ temperature_monitor_dir }}"
        update: true
      when: deploy_target_is_pi

    - name: Install required Python libraries with pip.
      pip: "requirements={{ temperature_monitor_dir }}/scripts/requirements.txt"

    - name: Configure the settings file (temps.conf).
      template:
        src: templates/temps.conf.j2
        dest: "{{ temperature_monitor_dir }}/scripts/temps.conf"

    - include: tasks/database.yml
    - include: tasks/app.yml
    - include: tasks/scripts.yml
