---
- hosts: all

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Ensure apt-transport-https is installed.
      apt: name=apt-transport-https state=present

  roles:
    - geerlingguy.mysql
    - geerlingguy.nodejs

  tasks:
    - include: tasks/database.yml
    - include: tasks/app.yml
