---
# Temperature montior vars.
temperature_monitor_dir: /vagrant

# Node.js vars.
nodejs_version: "0.12"
nodejs_forever: true

# Some defaults to make MySQL use less memory.
mysql_root_password: root
mysql_key_buffer_size: "16M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "128"
mysql_sort_buffer_size: "512K"
mysql_read_buffer_size: "512K"
mysql_read_rnd_buffer_size: "1M"
mysql_myisam_sort_buffer_size: "4M"
mysql_thread_cache_size: "4"
mysql_query_cache_size: "2M"
mysql_thread_concurrency: 1
mysql_innodb_file_per_table: "1"
mysql_innodb_buffer_pool_size: "16M"
mysql_innodb_additional_mem_pool_size: "4M"
mysql_innodb_log_file_size: "16M"
mysql_innodb_log_buffer_size: "2M"
mysql_innodb_flush_log_at_trx_commit: "1"
